server:
  port: 8084

spring:
  application:
    name: mssc-store21-users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: to-be-set
  threads:
    virtual:
      enabled: true
  rabbitmq:
    host: to-be-set
    port: 5672
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: to-be-set
    username: to-be-set
    password: to-be-set
    hikari:
      auto-commit: true
      pool-name: order-pool
      maximum-pool-size: 3
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false


rabbitmq:
  queue:
    audit:
      name: audit-queue
  exchange:
    name: topic-exchange
  routing:
    audit:
      key: audit-routing

aws:
  s3:
    bucket: iceplanet-stores
    region: eu-west-2
    accessKeyId: your-access-key
    secretAccessKey: your-secret-key

