server:
  port: 8084

spring:
  application:
    name: mssc-store21-users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/auth
  threads:
    virtual:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/store_authorization_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: password
    hikari:
      auto-commit: true
      pool-name: order-pool
      maximum-pool-size: 3
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false


order:
  openapi:
    dev-url: http://localhost:8083
    prod-url: https://store.factorialsystems.io

springdoc:
  api-docs.path: /v3/api-docs

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

